### ISSUE TITLE
Investigate using nodewebkit for all encompassed local jsbin

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#1150]
For schools, etc.

Server and client embedded in a single file with zero dependencies.

**Comment by johnlindquist** [comment]
@allouis Did you ever have any luck? Trying for the first time with
```
    "jsbin": "^3.11.23",
    "nw": "^0.12.0-alpha3"
```
 and running into weird from the coffee-script compiler when starting up:
```
ReferenceError: addEventListener is not defined
    at null.<anonymous> (/Users/johnlindquist/WebstormProjects/nwjs-jsbin/node_modules/jsbin/public/js/vendor/coffee-script.js:11850:47)
```

Any help would be awesome.

**Comment by johnlindquist** [comment]
Well, here's the required "hacks" until I figure out a better solution:
coffee-script, JSXTransformer, and less parsers all reference "document" (or addEventListener)

I had to go through and manually change ```document``` to ```window.document``` and ```addEventListener``` to ```window.addEventListener```.

Also, the less parser does an environment check for Browser/Node/Rhino.
```
} else if (typeof(window) === 'undefined') {
    // Node.js
```
Since nwjs *has* a window, but it's *still* node, I had to remove these checks.

I know this is not a solution, but it's "working".

**Comment by rogerwang** [comment]
@johnlindquist I guess the code in question is loaded in Node context. So the question is: should we keep a single context rather than Node/Window context split in NW? or Should we keep `window` undefined in Node context?

What's your opinion from user's perspective? I'm eager to hear from you because this would be an important decision we're going to make when preparing for nw13, which will be a major step forward from previous versions.

I filed an issue in NW to discuss this.
