### ISSUE TITLE
Console Panel: console.log(object) sorts by keys instead of the declared order.

### ISSUE THREAD

**Issue by nathanhammond** [jsbin/jsbin#1426]
This differs from the normal `console.log` and therefore counts as a bug to me. If you want to fix this I'll submit a PR.

**Comment by pygy** [comment]
This surprised me quite a bit, I though I had a bug somewhere in my code.

`for in` order is left unspecified because vendors could not agree on corner cases.

The general rule is that the insertion order is respected when iterating, and it is respected because "Web compatibility" TM.

In Chrome, integer-like keys are handled separately (I suppose their values are stored in an array) and are provided first.

In every browser but IE, deleting a key then recreating it pushes it to the end of the iteration list. In IE, the original place is preserved (probably leaking memory as you add and delete keys form the object).
