### ISSUE TITLE
Deleting a bin

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#1494]
Currently "Delete" deletes the specific revision (or "snapshot") of the bin, not the complete history.

I've had users specifically raise questions to me expecting the entire bin and all revisions to be deleted.

Options:
1. Don't support this, let users delete each revision individually - seems clunky
2. Delete all revisions by default - feels a bit scary
3. Offer both solutions (in the bin/file menu) - feels a bit "give the user more options"

Any preferences or alternatives?

I'm proposing option (3), the default keyboard action will delete the individual bin, and the [notification that appears](http://jsbin.com/help/delete-a-bin) can include a link to delete the full history if that was what was intended.

**Comment by ShuningTong** [comment]
I definitely agree with adding "delete all snapshots" for logged in users. I just started using JSBin, and was afraid of losing the work, so I hit Command + S very often assuming it will save my work. But later I found out in JSBin, Command + S stands for "create a new snapshot". Now I have like fifty snapshots for one bin. It's very annoying since for deleting each snapshot, I have to open that snapshot, hit Command + Shift + Delete, go back to all bins and open next one.
![screen shot 2017-01-16 at 2 53 01 pm](https://cloud.githubusercontent.com/assets/15147115/21997274/6e30da34-dbfc-11e6-83e3-60728e6c1397.png)

**Comment by copetus** [comment]
So how's this going? I'm having the same problem ShuningTong mentioned above...I've got 72 bins half of which I don't own ( whatever the reason for that is ). Why am i able to see them in myList of bins? I don't want to see bins that i don't own in my list. Can we get rid of those?
Also how does one create a bin anonymously?

I'd like to clean up myList but there's no way to select multiple bins or snapshots and delete them. I still have to select them one at a time and hit the weird shortcut.

**Comment by remy** [comment]
There's not been any pull requests that I've seen for this.
