### ISSUE TITLE
Default layouts

### ISSUE THREAD

**Issue by dannyhope** [jsbin/jsbin#2007]
We could add the ability to easily switch between a set of default layouts.

There could be corresponding buttons in the toolbar, like this 
![image](https://cloud.githubusercontent.com/assets/22055/4591184/1781b7ce-5069-11e4-8cdc-e2f73fdba4e7.png)

There could be a keyboard shortcut for cycling through them.

Later there could be a way of redefining the defaults (along with the ability to do a "factory reset" on them).

**Comment by kursion** [comment]
Pretty sad not to have different layout :( Anyway great job

**Comment by remy** [comment]
You can move the panels to your liking. Pro users also have access to the
layouts experiments.

**Comment by kursion** [comment]
How ? I tried multiple things but couldn't achieve to have this layout

```
__________________________
| HTML      |                                |
|--------------|         JS                   |
|CSS          |                                |
|_________|________________|
```

**Comment by remy** [comment]
It's not the same, but this:

<img width="922" alt="screen shot 2015-07-13 at 16 00 42" src="https://cloud.githubusercontent.com/assets/13700/8651320/5f4d2d66-2978-11e5-81a9-eaa4d4f64524.png">

Like I said though, the layout reconfig is under pro experiments: http://jsbin.com/help/experimental-features#morelayouts

**Comment by kursion** [comment]
Ahhh okay. Sorry didn't got it. Thanks :+1:

**Comment by apipkin** [comment]
Similar to how developer tools hides the different layout options in a drop down, I think this is easily possible in the current toolbar to the left or right of the profile option. This could support the current 7 and possibly more. 

I know currently there is only one that is resizable, but is this the long term goal? I think it would be very beneficial for different reasons (mostly because I just tried to resize the output row). If they were all made resizable, this would significantly minimize the complication of the icons used because there would be no need for the icons.

Predefined layouts is great, but also having the ability to configure new layouts would be great! I have yet to look at the structure for the layout manager, but having the ability to say options we have for each row or column would be great. 

```js
{ 
    layout: {
        type: 'row',
        rows: [
            {
                type: 'col',
                cols: [ 'html', 'css', 'js' ]
            },
             {
                type: 'col',
                cols: [ 'console', 'output' ]
            }
       ]
    }
}
```
A structure like this could be easily created by a UI and possibly easy to interpret by a layout engine. 

It wouldn't get an icon, but to @dannyhope's point, icons for the basic/generic/popular layouts, then the preferences pane for custom stuff. Maybe even and icon for "custom" to easily select your custom layout when you would like.
