### ISSUE TITLE
Auto-redirect to latest revision?

### ISSUE THREAD

**Issue by simevidas** [jsbin/jsbin#2184]
When sharing a JS Bin demo, sometimes I accidentally include the revision number in the URL (i.e. I forget to remove it from the URL). I usually improve my demos after sharing them, so revision-less URLs are the way to go, as users are always directed to my latest revision.

However, when I *do* share a URL with a revision number by accident, it would be cool if I could **subsequently activate** “auto-redirect to latest revision” so that e.g. jsbin.com/foo/3/ auto-redirects to jsbin.com/foo/.

---

How this could be implemented: Each demo has an additional “edgeAutoRedirect” field. When a jsbin.com/foo/3/ request comes in and that field is `true`, simply return a HTTP redirect response (302, 307, not sure what the optimal status code for this is) to jsbin.com/foo/. (PRO) users could set this field via checkbox in e.g. the Share menu of the demo.

**Comment by remy** [comment]
Pretty solid idea. Not quite sure where the option belongs. The bigger problem is the field is stored against a single revision, so if a user lands on a different rev, it wouldn't spot this field to redirect to the latest (short of searching all revisions which doesn't really make sense). It could be done at a user level, but it's unlikely you'd want it to apply to ALL bins (as you've suggested).

**Comment by simevidas** [comment]
Hm, auto-redirecting to latest might not be the optimal approach. After all, it would make that revision completely inaccessible since it would auto-redirect to the latest revision.

How about a banner with a “Click here to view the latest revision of this bin” link? It’s a less drastic approach which would enable bin authors to target specific revisions when there is a need for that.

I would add that banner myself but there’s no way to edit past revisions. JS Bin could have a standard banner for that, and bin authors would have the option to trigger its visibility for specific revisions.

**Comment by remy** [comment]
Hey @simevidas, a little late after the post, but a change (that I've been trialing for about 9 months) went live this w/e. The URLs now hide the snapshot by default. This means if you share the URL out of the browser, by default you're sharing the latest.

To select a snapshot, you need to open the share menu and select the snapshot URL you want. That fixes your kind of issue, but obviously the flip side is when people mean to share a version that's pinned to what they're looking at, rather than their changed code (i.e. I tweet "I've got this problem - here's a bin", then I noodle a bit and the shared bin isn't in the state I intended to share it in!). Tricky!

**Comment by simevidas** [comment]
The Share dialog looks great. You could also highlight the Share button, to make it stand out. Or add an icon, like a star or “new”.
