### ISSUE TITLE
FireFox Error

### ISSUE THREAD

**Issue by digitalwiz** [jsbin/jsbin#2450]
I have a JS Bin https://jsbin.com/jugopasuja/1/edit?js,console
I am running under Windows 8.1
This works correctly under IE, Safari and Chrome but under Firefox 38.0.5 I get errors in the console 

"error"
"@jugopasuja.js:13:6
k</b.render/<@https://static.jsbin.com/js/prod/runner-3.30.3.min.js:1:13601
j</a.use/<@https://static.jsbin.com/js/prod/runner-3.30.3.min.js:1:10524
"
![capture](https://cloud.githubusercontent.com/assets/1863076/8470824/55addcdc-205f-11e5-826f-81595c0bbb28.JPG)

**Comment by remy** [comment]
This is actually a Firefox thing that's caught me out before, and it's not specific to JS Bin...sort of.

Because JS Bin runs it's code inside of a try/catch in the iframe - so as to catch any errors relay them back to the custom console, it means your code is now in a scope.

The thing about Firefox is that once in a scope, it doesn't hoist functions (correctly according to the specification IIRC, _and_ to my surprise!). So, the solution is to move the function call *below* the function for it to work in Firefox.

Fun times, eh?

**Comment by digitalwiz** [comment]
Thank you
