### ISSUE TITLE
share imported gist

### ISSUE THREAD

**Issue by johanhake** [jsbin/jsbin#2510]
Hello!

Thanks for an excellent tool. I am developing a programming course based on JS and see jsbin as a natural helper. I might ask for a pro account when I have something to show ;)

I am using gist.github to post example code and I would like to show(share) these directly in my html. However, when I type:

```
http://jsbin.com/gist/johanhake/e00efa0e50bfe51e0882?html,output
```

I do not get a share button. I have to clone it first. But I would like to keep my (unreadable) gist hash. Is this possible? I also tried to inline the following text into the html:

```
`<a class="jsbin-embed" href="http://jsbin.com/gist/johanhake/e00efa0e50bfe51e0882/embed?html,output">HTML demo</a><script src="http://static.jsbin.com/js/embed.js"></script>`
```

But I only get:

```
503 Service Temporarily Unavailable
```

message.

Is this a bug or known limitation? If the latter, you might want to add a notice about that in the documentation of importing a gist, at:

```
http://jsbin.com/help/import-gists
```

Best regards,

Johan

**Comment by remy** [comment]
So, firstly the embed isn't supported for gists - but there's a bug that you're triggering (that's new to me) that causing jsbin to go into an infinite loop (which results in a 503 *for everyone*). Not good!

There's actually also another bug at play that's not rendering the gist properly (which is why there's some weird junk in the js panel - certainly there is for me) - I know what's causing this and can try to fix in the next few days.

As for getting a link, this is intentional. The user **must** enter text to create a new bin. You can't share because there's no real link to the bin yet, all you're seeing is an empty bin with a gist injected via the client side. 

The link you've already got is sharable, but jsbin's internals knows nothing about it. But, there's nothing stopping you from using those links in your posts, right?

**Comment by johanhake** [comment]
Thanks for looking into this! Sharing a gist the way I did would be a nice but not necessary feature.

So when I include:

    `<a class="jsbin-embed" href="http://jsbin.com/gist/johanhake/e00efa0e50bfe51e0882/embed?html,output">HTML demo</a><script src="http://static.jsbin.com/js/embed.js"></script`

in a web page the jsbin should be created client side while being embedded in the web page? However, a bug was triggered and it went into an infinite loop, right?

**Comment by remy** [comment]
Best case: yes, but support wasn't written intentionally. 

But yeah, it's not good right now, so please don't :)

**Comment by johanhake** [comment]
Ok, let me know if you fix it. Until then I will just clone the gist.
