### ISSUE TITLE
Yvesculptor.com mobile not working!

### ISSUE THREAD

**Issue by andreadams1974** [jsbin/jsbin#2580]
Hi~
I started creating mobile versions of websites using JS BIn back in 2013, and recently I noticed terms have changed. I signed up for the PRO Version, but I still cannot figure out how to PUBLISH my page or make updates, as I had done before! (in this case, for yvesculptor.com)

I also tried to Archive one of the Bins, but it says I need to "own it." (??)

I have paid the $20 monthly subscription, so why is it suddenly so difficult to publish pages when before it was a snap?

~Andre Adams
andreadams1974@yahoo.com
(831) 917-0971

**JS Bin info**
- [https://jsbin.com/edit](https://jsbin.com/edit)
- Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
- andreadams1974

**Comment by remy** [comment]
Just to clarify, the terms didn't change, they were added at the same time pro was launched (so these haven't changed since you upgraded to pro).

Looking at your username, I can see that your first bin was created on 10-Jan 2014 - that isn't to say you didn't use the site before, but under your current pro account, this is the first bin.

Regarding *publishing* - I'm not sure what you're referring to...can you clarify? There's never been a "publish" button on jsbin, except to publish to your vanity page, which again was introduced with pro.

Can you give me the url of the bin you're trying to archive? That might yield some clues...

**Comment by andreadams1974** [comment]
Hi Remy,
thanks for the quick reply....so when I say publishing--maybe I am not using the correct term?--I mean making edits to each page and making it live, as I had done previously. What I am trying to say is when I go in now and make revisions to the pages, those changes don't apply when I pull up the site on my mobile device.
The mobile version of the website I've been working on is : http://www.yvesculptor.com/
On the index page of that site I inserted code to redirect to the JSBin mobile version of the site. Hope this make sense now...
Here are a couple pages from the site...does this help?https://jsbin.com/lufijo/9
https://jsbin.com/netoxu/7

I just don't know what I need to do specifically in JS Bin to make the changes reflect when users go to http://www.yvesculptor.com/ and the mobile version comes up....??

ThxAndre Adams

**Comment by remy** [comment]
I'm still unsure of what you're seeing. But I have dug a little in your website code and spotted this:

```html
<script type="text/javascript">
  <!--
  if (screen.width <= 800) {
    window.location = "http://jsbin.com/pizoti/10/";
  }
  //-->
</script>
```

So you're doing a redirect to this bin when the screen width is small (not specifically mobile).

I'm guessing now that maybe you've hard coded the snapshot urls in the links? Certainly you have done in the redirect you're using, so maybe the right approach is to remove the snapshot in the url and therefore any changes to that bin are automatically picked up (because if you remove the snapshot, jsbin will serve the latest snapshot).
