### ISSUE TITLE
JS Bin snapshot

### ISSUE THREAD

**Issue by cleong14** [jsbin/jsbin#2601]
Hello, 

My jsbin has been auto snapshotting my bins at a ridiculous amount lately. I have around 800 bins because of it now. I wanted to know how to:
1. Stop the auto snapshotting, or at least minimize it to just enough so that I can recover my bin. Not to the point where I have hundreds of snapshots of the same bin.
2. Delete the snapshots to get my bin back to just the necessities.

Thank you in advance.

-Chaz Leong

**Comment by remy** [comment]
Snapshots only happen when you hit cmd+s (or ctrl+s) on the computer. There's no auto snapshotting.

**Comment by cleong14** [comment]
It seems to continuously save automatically for me. I guess in case my browser crashes, it'll auto save. But now my bins are piling up and a lot are of the same thing. Is there a way to mass select and delete bins?

Chaz Leong

**Comment by remy** [comment]
Not right now. It would be useful to get to the bottom of why it's saving
so much. Would it be possible to open a private browsing window and see if
you have the same problem? The aim here is the see if any extensions you
have in the browser are having an effect.

**Comment by thewazir** [comment]
I've encountered the same issue on IE 10 with no plugins. I can check on other browsers and see if it's a problem. I've noticed this for a while probably since this issue was first reported but I didn't realize it was a bug until today...

**Comment by thewazir** [comment]
No solution or exact idea what the problem is, but here are my notes so far.

Haven't had a chance to try on other browsers yet but on IE 10 I tried to see what JSBin was doing. On each keystroke the handler for the `codeChange` event is fired:
https://github.com/jsbin/jsbin/blob/master/public/js/chrome/save.js#L273


```
 $document.bind('codeChange', throttle(function (event, data) {
      if (!data.panelId) {
        return;
      }

      if (jsbin.state.deleted) {
        return;
      }

      var panelId = data.panelId;

      jsbin.panels.savecontent();

      if (saving.inprogress()) {
        // queue up the request and wait
        saving.todo[panelId] = true;
        return;
      }

      saving.inprogress(true);

      // We force a full save if there's no checksum OR if there's no bin code/url
      if (!saveChecksum || !jsbin.state.code) {
        // create the bin and when the response comes back update the url
        saveCode('save', true);
      } else {
        updateCode(panelId);
      }
    }, 250));
```

`saveChecksum` and `jsbin.state.code` both evaluate to `false` causing `saveCode('save', true);` to be executed. I'm not sure how or when `saveChecksum` and `jsbin.state.code` are set to `true` and why they aren't `true` whenever I use JSBin. Still need to dig thru this.
