### ISSUE TITLE
Babel in embeds (when jsbin is inside an iframe)

### ISSUE THREAD

**Issue by remy** [jsbin/jsbin#2630]
Example of issue:

![https://pbs.twimg.com/media/CUlAwfZWUAACZrV.jpg:large](https://pbs.twimg.com/media/CUlAwfZWUAACZrV.jpg:large)

Is this related to Babel or related to some iframe security change in Chrome...?

**Comment by joelhooks** [comment]
If anybody needs an egghead.io account to look at this, I'm happy to provide it.

**Comment by remy** [comment]
Example in devtools console on this url: https://egghead.io/lessons/javascript-redux-the-single-immutable-state-tree?series=getting-started-with-redux

**Comment by mikewest** [comment]
Does this work in Chrome Canary? If so, it was probably fixed by https://codereview.chromium.org/1261763003, and was probably caused by the properties returned from `for...in` coming back to you in a different order than you expected due to weirdnesses in bindings and V8 that happen from time to time.

**Comment by mikewest** [comment]
@joelhooks: May I have an account to poke at the problem?

**Comment by remy** [comment]
I can't actually sign in to egghead.io using Canary (some weirdness on the site). If I can, I'll confirm (or @joelhooks could?).

**Comment by joelhooks** [comment]
It does work in canary. @mikewest If you create an account I can upgrade it for you. I recommend creating a "normal" account versus the easy github oauth so you have a password.

**Comment by mikewest** [comment]
@joelhooks: https://egghead.io/users/64814

**Comment by joelhooks** [comment]
@mikewest you should be set

I've noticed similar issues with babel in the past. It was just intermittent. Yesterday we released a course that was all babel, so it was highlighted.

**Comment by mikewest** [comment]
@joelhooks: Thanks. I don't see the error in dev channel or Canary. I do see it in stable, so, let me take a closer look.

**Comment by mikewest** [comment]
So, babel is doing something like:

```
for (var k in window) {
   if (!blacklistedKeys["$" + k] && has.call(window, k) && window[k] !== null && typeof window[k] === "object") {
    // do interesting things here.
  }
}
```

That worked in older versions of Chrome, because it relied on the order of things returned from `for...in` loops to return whatever it was looking for before things like `window.frameElement`. Chrome helpfully throws a `SecurityError` when accessing those kinds of cross-origin objects. We've since changed our behavior (and the spec) to match Firefox's behavior of returning `null` rather than throwing.

While you wait for Chrome ~48, wrapping that loop body in a `try...catch` will solve the immediate problem.

**Comment by mikewest** [comment]
(None of that explains why it would have started happening yesterday; this code has been broken in this way for a few weeks now.)

**Comment by joelhooks** [comment]
@mikewest it didn't start yesterday, was just noticed at a bigger scale :>

**Comment by gaearon** [comment]
@mikewest Thank you for investigating!

**Comment by shidhincr** [comment]
This is still broken and affecting the code embedding everywhere. I was trying the CycleJS examples, and found that none of the JSBin embed is working.

Try here:
http://cycle.js.org/basic-examples.html

**Comment by remy** [comment]
@shidhincr didn't @mikewest explain that this is a) a Chrome thing that will trickle down as a fix once it's moved from Canary to stable, or a fix for Babel - since it's outside the realm of what jsbin can do?

**Comment by shidhincr** [comment]
Ah .. my bad! I wrote that comment thinking I was trying in Chrome canary.. Thanks @remy.. Let me try in Canary

**Comment by remy** [comment]
Closing if solved by chrome update or babel update (which sounds kinda lame...).

**Comment by shidhincr** [comment]
@remy Yeah.. The issue is no more in latest Chrome.  :+1:
