### ISSUE TITLE
Ability to clone a bin via the API

### ISSUE THREAD

**Issue by joelhooks** [jsbin/jsbin#2704]
as a subscriber, I would like to have the ability to clone bins by ID via the API so that I can stop seeing errors when I accidentally embed from a third party bin.. 

Similar to existing `save` endpoints, but not requiring parameters. Would function in the same fashion as `file>clone`, and should return the newly cloned bin.

**Comment by remy** [comment]
The API is currently considered experimental (and therefore could be dropped), but I'll consider this feature request. It seems entirely sensible (or accept a PR adding this to the current API). 

I think it's fine, since only pro users can use the API, but cloning is an edge case that needs to be carefully protected so that users can't abuse it and en masse generate duplicate bins (typically used to create spam or abuse in high numbers). Worth keeping this in mind with any work around cloning.
