### ISSUE TITLE
Editor settings not persisting on local version

### ISSUE THREAD

**Issue by jtfell** [jsbin/jsbin#2710]
I have a local version of JsBin running and everything works as expected except the editor settings aren't persisting correctly. I have inspected the sqlite database and the changes are being saved there, but they aren't being applied to the editor and have also reverted back to the defaults in the settings window.

To replicate:
- Login
- Open Account > Editor settings
- Change something (reports that settings are saved)
- Back to JSBin
- Open Account > Editor settings
- Changes aren't persisted

**Comment by remy** [comment]
If you have a local version do you want to debug and send a PR?

**Comment by jtfell** [comment]
I've had a deep look into what is wrong, but can't isolate the issue. It seems like the user.js file does not contain the settings element, but that is not the only problem. Even if I hardcode it to add one in, the editor doesn't interpret it anyway. Do you have any intuition into what (or where) the problem might be?

**Comment by remy** [comment]
So, IIRC, local storage is used to maintain "local" state and preferences.
Then, if the user changes then via their account prefs, then *that* should
override (and appear in the user.js object).

Then finally if the user has a panel name on the query string then that
rules over all.

I think it happens in editors.js (in public) and fair warning, the code is
a bit of a mess!

I think it's worth dropping the local storage support since this was a
stopgap solution whilst there was no concept of a user, and I think that's
messing with the logic.

**Comment by jtfell** [comment]
Ok thanks for that. The thing that really mystifies me is that it works fine on jsbin.com, but the same code doesn't work the same for me. Is there any specific server config that's needed?

**Comment by remy** [comment]
Ah, no, it doesn't work fine on jsbin.com! There's some reports of exactly this issue on the live site.

**Comment by with0out** [comment]
Wish local version could persist editor settings...
