### ISSUE TITLE
ReferenceError: createStore is not defined

### ISSUE THREAD

**Issue by zhouhao27** [jsbin/jsbin#2749]
My html:

```
<!DOCTYPE html>
<html>
<head>
<meta name="description" content="TodoApp">
  <meta charset="utf-8">
  <script src="https://fb.me/react-0.14.7.min.js"></script>
  <script src="https://fb.me/react-dom-0.14.7.min.js"></script>    
  <script src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.5.1/redux.min.js"></script>
  <title>React Demo</title>
</head>
<body>
<div id="app"></div>
</body>
</html>
```

My babel/es6 Javascript:

```
const todos = (state = [], action) => {
  switch(action.type) {
    case 'ADD_TODO':
      return state.concat([action.text]);
    default:
      return state;
  }
};

let store = createStore(todos, ['This is a initial state']);

store.dispatch({
  type: 'ADD_TODO',
  text: 'Another todo'
});

console.log(store.getState());
```

The error message is:

> "ReferenceError: createStore is not defined at dezumix.js:14:13"

**Comment by zhouhao27** [comment]
```
const {createStore} = Redux;
```

Solve the problem. But:
```
import {createStore) from 'redux' 
```
doesn't work.

**Comment by marcelopereirascmspain** [comment]
@zhouhao27 I think imports will not work with any module, not just Redux. And this is not really an issue with jsbin.
Just open the file https://cdnjs.cloudflare.com/ajax/libs/redux/3.5.1/redux.js and you will see that if you run these expressions in a bin, you will get undefined for all of them. The fallback is to set the module as a global variable on window. That's why `const {createStore} = Redux;` works. You are just destructuring `createStore` from `Redux`.

```javascript
console.log(typeof exports); // "undefined"
console.log(typeof module); // "undefined"
console.log(typeof define); // "undefined"
```
