### ISSUE TITLE
Export JSBin to Gist does not link to GitHub account

### ISSUE THREAD

**Issue by dw-roth** [jsbin/jsbin#2757]
According to the link below, exporting a jsbin as a gist should link it to my github account if my jsbin account is linked to github (which it is). This isn't working. The exported gist is anonymous.

https://jsbin.com/help/export-gist

Apologies if this is a dup.

**Comment by clearbug** [comment]
I'm having the same issue.

**Comment by robin-a-meade** [comment]
Me too. If I log in via GitHub that should be sufficient to link to my github account, right?

**Comment by cortazar11** [comment]
So what is going on?

**Comment by ctammes** [comment]
Same problem here.

**Comment by designviacode** [comment]
same issue here .. !!

**Comment by onthisearth** [comment]
I'm having the same issue.

**Comment by neaumusic** [comment]
bump

**Comment by remy** [comment]
No need to bump. Just send a PR.

**Comment by alarsn** [comment]
Following, having the same issue.

**Comment by CollinChaffin** [comment]
Also was just bitten by this bug.  As a new JSBIN user this is pretty bad when you "think" you've set it up as prompted, just to export something you believe will be allowed as a secret/unlisted GIST (because I am logged in to Github and accts linked), just to have the code put out into a public Gist that cannot even be removed then without screwing around and contacting Github support.

This needs to be fixed, or if it's going to sit for another 6 months like it has without any visible work on the issue, perhaps just update that option in your GUI (which is a simple tooltip string update that takes 30 seconds) to indicate it is currently broken and only exports ANONYMOUS Gists!  

JSBin has tags all over asking to pay to upgrade to pro but as a brand new user of JSBIN, I have a hard time doing that when right off the bad a major export feature of the tool has a critical bug and I come here and a FULL YEAR has passed and the DEVs haven't done anything to fix it, or even tell their users it is actually being worked on!   It is just too concerning, before purchase, as to what other major "PRO" features may be sitting in the same broken state and also being ignored.

**Comment by remy** [comment]
A fix was merged a few weeks ago. But please do take your self righteousness and try out codepen or jsfiddle. I'm confident they'll suit your requirements just fine. I'm quite serious. 

(Closing as i mentioned, this was fixed, by someone who actually contributed to the open source project in a positive manner).
