### ISSUE TITLE
while loop terminating prematurely

### ISSUE THREAD

**Issue by chrisbay** [jsbin/jsbin#2778]
In [this bin](http://jsbin.com/damecu/edit?js,console) the while loop executes only once, even when `isNaN` should return false (e.g. with input 'a') and result another execution.

Testing this code directly in a webpage or in Firebug results in expected behavior.

**Comment by jrstanley** [comment]
This is JS Bin's [infinite loop protection](https://jsbin.com/blog/protection) kicking in, you should see the below warning;

> Line 4: Exiting potential infinite loop. To disable loop protection: add "// noprotect" to your code

This is triggered because the loop takes more than 100ms to execute, given that you are synchronously waiting on user input from prompt(). The [loop-protect repository](https://github.com/jsbin/loop-protect) is available on GitHub too.

You can see [an example with // noprotect](http://jsbin.com/wunoqes/3/edit?js,console) which seems to work.

Furthermore, if you share your bin as 'Output only' ([example](http://jsbin.com/dozeci)) the protection is not applied in any event.
