### ISSUE TITLE
Vim Commands

### ISSUE THREAD

**Issue by davidgklein** [jsbin/jsbin#2826]
I am using the Vim keybindings, and when I type a command, I don't see it appear anywhere on the screen as I'm typing. The commands seem to work fine, but I'm having some difficulty doing text search and replace without being able to see the commands that I'm typing. Thanks in advance for any help.

**Comment by baygeldin** [comment]
Hi, I had the same problem. I checked which CSS classes are used in CodeMirror to style command input (using handy DOM breakpoints in Chrome) and styled them so that the input could be seen. Actually, I didn't even had to style them myself, 'cause I found a useful tampermonkey script and just adjusted it a bit. Here is is (you can just copy paste it and it should work):
```javascript
// ==UserScript==
// @name         JS Bin Toolkit
// @version      0.1
// @description  Different useful utils for JS Bin.
// @author       Alex Baygeldin
// @include      *://jsbin.com/*
// @grant        GM_addStyle
// ==/UserScript==

// Fix styles for Vim command mode.
GM_addStyle(
  '.CodeMirror-dialog{position:absolute;left:0;right:0;background:rgba(204,204,204,0.5);z-index:15000;padding:.1em .8em;overflow:hidden;color:inherit}' +
  '.CodeMirror-dialog-top{border-bottom:1px solid #eee;top:0}' +
  '.CodeMirror-dialog-bottom{border-top:1px solid #eee;bottom:0}' +
  '.CodeMirror-dialog input{border:none;outline:0;background:0 0;width:20em;color:inherit;font-family:monospace}' +
  '.CodeMirror-dialog button{font-size:70%}'
);
```
