### ISSUE TITLE
Tabs top dropdown changed to "Processor"

### ISSUE THREAD

**Issue by caub** [jsbin/jsbin#2843]
![image](https://cloud.githubusercontent.com/assets/3134574/17561198/48d60d3a-5f25-11e6-8f9a-958e56b7e223.png)

it's interesting, but note that it's not obvious which tab in CSS / JS, "Processor" every where doesn't convey a lot of information

**Comment by remy** [comment]
Hmm. Interesting. The 2nd person to note an issue with this.

I'll give it a rethink. It was changed because many didn't know that this
was how to change the processor, and the information as to what language it
was is replicated. I get your point specifically regarding CSS and
JavaScript in the empty state.

**Comment by caub** [comment]
ah I see.. meh, normally the  ` JavaScript▾`  explicitly tell to click to see more.

If it were me I'd even group those options in the top toggle buttons :), saves place, but potentially confusing

**Comment by jeserkin** [comment]
Noticed it as well. Would be nicer, something like `Processor: SELECTED_PROCESSOR`.

**Comment by remy** [comment]
No intention to make the label longer than it has been historically.

A settings cog is the one item that's come up before (but it would be next
to the panel name)

**Comment by jeserkin** [comment]
There is no need to make it longer. There is always a choice to use `title` attribute for example or add some sort of marking in dropdown list so that it would be clear, what is selected at the moment. All those options don't make label longer.
