### ISSUE TITLE
Group access to bin

### ISSUE THREAD

**Issue by iain87** [jsbin/jsbin#2943]
Hi, is there a way to allow group editing access to a bin or ideally a library of bins? We are using the bins for Greasemonkey scripts and as they auto-update based on a single url, we would like to have any person on the team be able to make the change rather than just the original owner.

**Comment by remy** [comment]
It's something I've started investigating, but it's a simple change (due to the arch of jsbin's bin ownership). It's something I've had enquiries to commission, and it's likely to be available to paying users (in some way), but unless there's a financial drive to invest in the change, I don't have the resource (sorry, this sounds a bit money-grabbing, but just trying to offer some insight into the process for bigger changes).
