### ISSUE TITLE
Files that displayed correctly last week are not now--UPDATE

### ISSUE THREAD

**Issue by JoAnn21** [jsbin/jsbin#2986]
In January I submitted an issue that my file was not rendering correctly. The issue was closed out, with no resolution. I placed the code into other code sites and had no problems with the files (actually 2 separate files.) Yesterday, to my surprise, both files rendered correctly in JSBin. I was happy, since I'd rather do my classwork on this site. However, today I open both files, and the exact same problems are back in both files--the horizontal navs are not displaying as they should. The code is correct, renders fine elsewhere. Any idea what is going on here?

https://jsbin.com/ruhucu/10/edit?html,output

https://jsbin.com/sewiteb/4/edit?html,output

Thanks.

Prior close out e-mail:
Last week nav displayed correctly. Since end of last week, now nav bar is not appearing correctly--never changed any code. Appears correctly in Dreamweaver, but I need to use JSBin for classwork. Help please.

https://jsbin.com/hemosi/2/edit

**Comment by remy** [comment]
This isn't a JS Bin issue - which is why the original issue was closed. 

Looking at your links, you're using https to serve the jsbin pages, but using http when referring to the bootstrap CSS, so the CSS isn't loading. This is normal browser security behaviour. 

A few recommendations: use https everywhere. If you have rendering issues, download (using the download link the navigation menu) the file and open in the browser, and debug from there.

**Comment by JoAnn21** [comment]
Thank you! Will do--I am a beginner, so it is all a bit overwhelming right
now. Any suggestions are very helpful.

Regards
