### ISSUE TITLE
I can't login to jsbin

### ISSUE THREAD

**Issue by EljamRussell** [jsbin/jsbin#3016]
1.  Click on Login or Register.
2. Click on Login or Register via GitHub
3. It says: "Sorry, that GitHub account is linked to another JS Bin account."

I already registered though via GitHub.  Any help on how to login please.

**Comment by remy** [comment]
Can you try an incognito window?

**Comment by EljamRussell** [comment]
Thank you, it works!  I just wonder why.

**Comment by aiham** [comment]
@remy I had this issue too, clearing my cookies fixed it. You should probably look into this. I've had the same issue on a project of mine which ended up sending 2 cookies with the same name to the server. It probably happens due to a change in the Set Cookie value, maybe a change in the path parameter: https://stackoverflow.com/questions/4056306/how-to-handle-multiple-cookies-with-the-same-name
