### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rtwk** [jsbin/jsbin#3121]
Trying to install jsbin locally. Cloned the repo with git clone. cd to the directory and then run 'yarn install'.
Error : error jsbin@4.0.5: The engine "node" is incompatible with this module. Expected version "7"

**Comment by vdavid** [comment]
It's because of the `"engines": { "node": "7" },` part of `package.json`.

Installing Node 7.x resolved the issue for me.

To do it, I followed this method on my AWS EC2 (Amazon Linux): https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html
(did an `nvm install 7.10.1`)
