### ISSUE TITLE
When HTML set to Markdown page doesn't render when only output selected

### ISSUE THREAD

**Issue by hryanjones** [jsbin/jsbin#3156]
I have a [bin that has HTML set as markdown with some content](https://output.jsbin.com/wewakeh). I can edit this bin, but whenever I go to the output link (as above) I get a **504 Gateway Timeout**. I've tried in Chrome and Firefox. This seems to happen every time I convert the HTML to markdown, [here's another example](https://jsbin.com/sucigop).

**Comment by hryanjones** [comment]
This appears to still be an issue. 

tried at one point to set up jsbin so that I could maybe tackle it myself, but ran into issues npm installing things.

**Comment by remy** [comment]
I've just worked on this in version 5 of jsbin - now correctly working. The source of this bug is twofold:

1. bin-to-html was corrupted as it was inserting the CSS in the wrong position (fixed in [this commit](https://github.com/jsbin/bin-to-file/commit/ce6f5ac799cd85b87656dbd7fc35a799dae23e4a))
2. Server side markdown is hanging - this is completely removed in v5 as the full rendered source will be directly available and there won't be any reliance on a serve job.

**Comment by hryanjones** [comment]
Awesome! Thank you!

**Comment by hryanjones** [comment]
Reopening because it looks like this issue has returned. [bin I see the issue on](https://output.jsbin.com/wewakeh)
