### ISSUE TITLE
JSBin `protect` code messing up loops still

### ISSUE THREAD

**Issue by josephrocca** [jsbin/jsbin#3272]
Here's an example: http://jsbin.com/becelidazi/3/edit?html,js,output

![image](https://user-images.githubusercontent.com/1167575/45013877-3c936e00-b04f-11e8-924a-fbb88619d017.png)

Notice that it breaks the string strangely:
```javascript
      if (state.lexical.type == "stat") indent = state.lexical.indented;
      else {;window.runnerWindow.protect.protect({ line: 327, reset: true }); for (var outer = state.lexical; outer && outer.type == "){
if (window.runnerWindow.protect.protect({ line: 327 })) break;
" && outer.align; outer = outer.prev)
}}
```

I don't know whether jsbin is being maintained anymore, but I figured I'd post it anyway. Still has this issue too:

![image](https://user-images.githubusercontent.com/1167575/45013903-5634b580-b04f-11e8-9094-28db9cb96d09.png)

---

Edit: Ah, I see a full rewrite of jsbin is coming - very cool! Btw, for others, the workaround is to just not use the JavaScript tab - embed it in the HTML instead.

**Comment by remy** [comment]
Yeah, there's logic bugs in the old loop protect. The rewrite is available to test on v5.jsbin.com if you want to try your test case.

**Comment by binki** [comment]
I noticed a loop messup with this simple code:

```js
document.body.textContent=(() => {
  var x=0,j=0;
  for (;j<25;j++)x+=1;return''+x;
})();
```

I get the answer 1 in the live preview window but 25 when I pop the window out. Until I started suspecting JSBin of transforming the JavaScript, I thought that `return` had yet another weird newline behavior beyond [the well-known gotchas](https://stackoverflow.com/q/8528557/429091). Then I realized it only happened in JSBin. I was just about to file this issue but noticed the bug still exists.

I was trying to see what the transformed JavaScript looks like when jsbin messes with it but couldn’t figure out how to view it. Is there any way JSBin could show what the JavaScript is transformed to when using the live view? This could help users a lot because normally we trust JSBin and tools like it to only use, e.g., stable and widely used babel transforms or use the provided JavaScript verbatim. Tools like JSBin are normally used to play with oddly-written JavaScript in the first place, so it should behave like a real JavaScript interpreter/browser when it can.

**Comment by binki** [comment]
The v5 appears to work with my loop code.

**Comment by josephrocca** [comment]
@remy, does [Site Isolation](https://developers.google.com/web/updates/2018/07/site-isolation) impact whether v5 will need the infinite loop protection stuff?

> Site Isolation is a recently introduced feature in Chrome that runs a separate renderer process for each cross-site iframe. We’ve been talking about one renderer process per tab model which allowed cross-site iframes to run in a single renderer process with sharing memory space between different sites. Running a.com and b.com in the same renderer process might seem okay. The Same Origin Policy is the core security model of the web; it makes sure one site cannot access data from other sites without consent. Bypassing this policy is a primary goal of security attacks. Process isolation is the most effective way to separate sites. With Meltdown and Spectre, it became even more apparent that we need to separate sites using processes. With Site Isolation enabled on desktop by default since Chrome 67, each cross-site iframe in a tab gets a separate renderer process.

https://developers.google.com/web/updates/2018/09/inside-browser-part1

I guess it might be worth including anyway - the only down-side is that it makes debugging with devtools slightly weird, but that's a very minor thing.

**Comment by binki** [comment]
.
