### ISSUE TITLE
can't use name as a name for new object

### ISSUE THREAD

**Issue by mohammadameer** [jsbin/jsbin#3308]
when using " name "  as  an identifier for the new object I can't access its properties
link to the problem https://jsbin.com/maveyoj/edit?js,console

and this is a sample of the code 
```
var name = {
  first: "mohammad"
};

console.log(name.first); // i think the right is to see "mohammad" but it give udefined
```

**Comment by bruceontheloose** [comment]
Hi, @mohammadameer,

I see you posted this a couple weeks ago so you might know the answer by now. If not, the `undefined` message you're seeing isn't due to a JS Bin bug. Here is an explanation:

  https://stackoverflow.com/questions/10523701/using-the-variable-name-doesnt-work-with-a-js-object

Your code does work if you use the `const` or `let` variable type instead of `var`. (If those are new to you, they're very much worth reading up on.) Here's a modified version of your code, using `const`:

  https://jsbin.com/helejatuxa/1/edit?js,console

Hope that helps,

Bruce

**Comment by mohammadameer** [comment]
👍 👍 👍  thanks, there is window.name
