### ISSUE TITLE
Multiple JS files

### ISSUE THREAD

**Issue by yanko** [jsbin/jsbin#355]
You could have it when downloading a project ...save it like you do now,
but give us an option to be able to spacify a tab(view) for lets say game object, AI and Player objects...
i am experimenting now and have to scroll up and down all the time...it gets hard to work  around it

you could add a JS File button beside Share and have a dropdown menu with  
game.js
player.js
ai.js
new js file

thank you!!!

**Comment by ramtob** [comment]
I'd want the multiple files feature too. Multiple HTML files are also relevant, at least for Angular (multiple views).

**Comment by remy** [comment]
We have no way to implement this, and multiple bins works around this.

**Comment by ramtob** [comment]
Multiple bins is a workaround. However (1) if you need, say, 5 js files, you'll need to create at least 4 bins, for the same project.. (2) With multiple bins you don't have meaningful file names. Instead of e.g. controllers.js, services.js, you'll have jsbin random names, like wecen.js, jeviqa.js, and such..

But maybe this is too much to ask from jsbin. It is a already a great environment.

Thanks

**Comment by jimmywarting** [comment]
+1

**Comment by remy** [comment]
A `+1` doesn't buy anything here. PRs and feedback helping those on PRs is the only currency.

**Comment by r7lemieux** [comment]
I cannot demo a simple angular app with jsbin. I do not know how to make the import work with the bins.
