### ISSUE TITLE
nib support

### ISSUE THREAD

**Issue by QaDeS** [jsbin/jsbin#379]
In theory, it's as simple as
stylus(source).use(require('nib')())
I just couldn't figure out how to package a working nib into the public/js/vendor folder. Which tool do you use for that?

**Comment by loginx** [comment]
I don't think browserifying nib would work, because AFAIK the stylus compilation is done on the server-side.

You'd need to add nib to `package.json` and then a user would presumably be able to add `@import 'nib'` to the top of their stylus directives to enable nib.

Or you could add a bit of UI sugar through a checkbox to automatically add/remove that import statement so that users who aren't aware that nib is installed are able to discover the feature.
