### ISSUE TITLE
[Feature Request] - Renaming and Search feature

### ISSUE THREAD

**Issue by sachinjain024** [jsbin/jsbin#868]
One of the good features can be renaming your bins and searching it later on. Most of the times I do experimentation on jsbin and often struggle to find out my previous bins.

**Comment by jcrben** [comment]
Agreed that this would very helpful for organizing the code.

**Comment by remy** [comment]
This is two features. Renaming requires a UI, and currently I'm
prioritising ui-less work.

Search is a complex and large topic. I plan to use elastic search, but
what's a good search? What if I search for "body"? What kinds of things are
you thinking you would search on? This would help understand the problem
better.

**Comment by jcrben** [comment]
OK, I'm mostly interested in the renaming or at least titling, and even further folders or tags to organize - so UI stuff. The use case is to organize scripts which demonstrate simplified core concepts for myself, kind of like snippets, versus my current practice of storing such things in Sublime projects.

As far as search, I'm not sure I'd use that much. I would prioritize Codepen-style portfolio displays (may have that to some degree with your vanity pages, I'm not sure) as that seems to be one of the main things drawing people to Codepen.

I'd like to try hacking around on it a little bit, but I have not got it to run locally due to some sqlite node-gyp and libzmq dependency (though I think the latter is fixed - will post an update).

**Comment by blunderboy** [comment]
Remy,

I understand this is two issues technically but from user point of view I
feel this in one feature.
Things I always wanted are:
1. Provide Name and Description to your bin
2. Search your bin later (Search runs on Name and description fields only)


Currently, I do not know any way to manage my bins. Is there anything which
I am not aware of ?

**Comment by remy** [comment]
@blunderboy search and organise are two distinct features. 

You've said you don't know of any way to organise your bins, you can delete and archive, that's *one* way, but it's not what I think you want to do.

@jcrben tagging is fairly low hanging fruit, and there's a table already in place that can help with this (I've been using it privately to "star" other bins): `owner_bookmarks` - but you're right, there's UI work here, both to allow the user *to* tag and to show the tags. 

I don't use codepen, partly because I don't want to "borrow" features from them, but also because I'm not the audience. JS Bin is very much focused around teaching and learning, a quiet practise. CodePen (to me at least) is mainly for the designer community to show off their work. JS Bin is less about showing off and more about helping others. 

The vanity page is one way that a user could replicate this functionality, and there's an API for listing all your bins so that it could be managed in a portfolio manner or even snippets.

Perhaps snippet + API support is the initial way to go?

Re: search - this is a large chunk of work, and given that it's just me, it's unlikely to rise to the top for quite a long time. If someone else comes in with a fully prepared ES solution and UX work, then I'd be happy to accept it.

**Comment by andzi** [comment]
can't find how to rename (if it's already implemented)

**Comment by heroselohim** [comment]
**Search** is almost a required feature to use JSBin as **code storage**. I wouldn't care if it is added for PRO users. In fact I would became a PRO user only for that feature.

**Rename**? You can change the meta description and that changes the name:

`<meta name="description" content="Vue 2.0 Testing and Learning syntax - Renaming Bin">`

**Comment by jiiieff** [comment]
I love jsbin. I wish there was a better way to store and organize the code for searching later.
