### ISSUE TITLE
%2C or %252 in URL is not interpreted as a comma, shows wrong screens

### ISSUE THREAD

**Issue by wraybowling** [jsbin/jsbin#890]
When using the "Share" feature, I wanted to show just JS and the Console. When the link is made, the URL includes a comma. When the link goes back out through Facebook (in this case) that comma is converted to %2C and then jsbin doesn't pick up the URL to show the right screens.

example: http://jsbin.com/IkIwEYu/7/edit?js%2Cconsole

**JS Bin info**
- [http://jsbin.com/IkIwEYu/13](http://jsbin.com/IkIwEYu/13)
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.69 Safari/537.36
- rgbk

**Comment by samsam-ahmadi** [comment]
I have the same problem in Hugo (gohugo.io)
this is  layout in hugo :
`<iframe class="" id="" data-url="http://jsbin.com/{{.Get "id"}}/embed?{{ if not (eq (.Get "tabs") "") }}{{ .Get "tabs" }}/{{ end }}" src="http://jsbin.com/{{.Get "id"}}/embed?{{ if not (eq (.Get "tabs") "") }}{{ .Get "tabs" }}/{{ end }}" style="border: 1px solid rgb(170, 170, 170); width: 100%; min-height: 300px; height: 38px;"></iframe>`

and in the md file is : 

`{{< jsbin id="newohi" tabs="js,output" >}}`

but when page load in the iframe, I get the %2c instead of a comma in URL  and tabs isn't I want.
![screenshot from 2017-04-09 22-29-37](https://cloud.githubusercontent.com/assets/18388480/24839662/13f20714-1d74-11e7-8946-8e7fa695095d.png)
